# Generated by Django 4.1.3 on 2022-11-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental_reservations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="previous_reservation_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
