# Generated by Django 4.1.3 on 2022-11-11 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rental_reservations", "0002_reservation_previous_reservation_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation", name="previous_reservation_id",
        ),
    ]
